### PR TITLE
Upgrade conan

### PR DESCRIPTION
**Pull request by DanielKrawisz**
This pr upgrades to conan 2 and removes websocketspp, since we were not able to get that library to work.

### CODE REVIEW

**Comment by owenkellogg** [comment]
Looks good, since we decided upon plain boost asio for websockets anyway.

**Review by stevenzeiler — COMMENTED** [review]
Looks good to me :thumbsup:

**Comment by DanielKrawisz** [comment]
Can you please accept this pr or give me write access @owenkellogg ?

**Comment by stevenzeiler** [comment]
Yes, merged and you are now an admin of this repo.

**Pull request merged**
